apiVersion: v1
kind: Service
metadata:
  name: skillupjava-cicd-service
spec:
  ports:
    - protocol: "TCP"
      port: 8786
      targetPort: 8786
  selector:
    app: skillupjava-cicd
  type: NodePort